// This file was autogenerated by ./lib/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../app.js', ['BB.go'], ['BB.RecPlayer', 'BB.Session']);
goog.addDependency('../../../bb.js', ['BB.Frame', 'BB.RecPlayer', 'BB.Recording', 'BB.Session', 'BB.go'], []);
goog.addDependency('../../../promo-site/bb.js', ['BB.Frame', 'BB.RecPlayer', 'BB.Recording', 'BB.Session', 'BB.go'], []);
goog.addDependency('../../../src/BB/Frame.js', ['BB.Frame'], []);
goog.addDependency('../../../src/BB/RecPlayer.js', ['BB.RecPlayer'], []);
goog.addDependency('../../../src/BB/Recording.js', ['BB.Recording'], []);
goog.addDependency('../../../src/BB/Session.js', ['BB.Session'], ['BB.Frame', 'BB.Recording']);
