// This file was autogenerated by ./lib/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../app.js', ['app.go'], ['BB.Session']);
goog.addDependency('../../../src/BB/Frame.js', ['BB.Frame'], []);
goog.addDependency('../../../src/BB/Session.js', ['BB.Session'], ['BB.Frame', 'goog.dom']);
