// This file was autogenerated by ./lib/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../app.js', ['app.go'], ['BB.Frame']);
goog.addDependency('../../../src/BB/Frame.js', ['BB.Frame'], []);
