<div id="top" class="jumbotron">
   <div class="container">
      <img src="/assets/img/big-brother-js-logo.png"/>

      <h1>BigBrother.js</h1>
      <p>Visual user monitoring & website analytics</p>
   </div>
</div>

<div class="container">

   <h3 id="tour" class="subhead">Watch real users navigating your website</h3>

   <div class="row">
      <div class="col-md-12">
         <img src="/assets/img/mock-video-player.png" class="img-responsive" style="width: 80%; margin: 10px auto">
      </div>
   </div>

   <div class="row">
      <div class="col-md-10 col-md-offset-1 text-center">
         <h2>What it is</h2>
         <p>BigBrother.js is a free and open-source website analytics library. It focuses on providing <strong>visual data and analysis</strong> about your users. With BigBrother.js you can see <strong>click heatmaps</strong> for each page or page category of your website, as well as <strong>watch recordings of your users navigating each page of your website</strong>. BigBrother.js also allows you to watch aggregate recordings of users' sessions, so you can quickly see what the most common behavior and usage patterns are from real users and consumers of your site and application.</p>

         <hr/>
         <h2>How it works</h2>
         <p>By including BigBrother.js JavaScript library on your website, every action your user takes on your site is recorded and saved for later analysis and playback. Since the library is compact and small in size, as well as highly optmized for low memory usage and high performance, users will never notice that BigBrother.js is running on the background.</p>
         <p>As more users come to your website and have their sessions recorded and tracked by BigBrother.js, you can then view click heatmaps for individual pages and page categories, as well as watch individual or aggregate session recordings from those users.</p>

         <hr/>
         <h2>How to use it</h2>
         <p>Using the library could not be any simpler; all you need to do is drop in the JavaScript tag to import BigBrother.js into your page, sit back and wait for your users to come to your site, then view the reports generated by BigBrother.js.</p>

         <div class="row">
            <div class="col-md-4 col-sm-6 benefit">
               <div class="benefit-ball">
                  <span class="glyphicon glyphicon-screenshot"></span>
               </div>
               <h3>Tracking Code</h3>
               <p>Include BigBrother.js JavaScript library on pages you want to track.</p>
            </div>

            <div class="col-md-4 col-sm-6 benefit">
               <div class="benefit-ball">
                  <span class="glyphicon glyphicon-user"></span>
               </div>
               <h3>Monitor Users</h3>
               <p>Every user that comes to those pages is monitored quietly and discretely.</p>
            </div>

            <div class="col-md-4 col-sm-6 benefit">
               <div class="benefit-ball">
                  <span class="glyphicon glyphicon-play"></span>
               </div>
               <h3>Playback</h3>
               <p>You can then view click heatmaps and watch session recordings.</p>
            </div>
         </div>

         <hr/>
         <h2>Get Started</h2>
         <p>Ready to start tracking and monitoring your users like you work for the NSA?!</p>
         <p><a href="/download" class="btn btn-lg btn-success"><span class="glyphicon glyphicon-download-alt"></span> Download BigBrother.js</a></p>
      </div>
   </div>
</div>